import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import { Navbar } from "@/components/layout/Navbar";
import { Footer } from "@/components/layout/Footer";
import { ThemeProvider } from "@/providers/NextThemesProvider";
import { DiagonalLines } from "@/components/ui/DiagonalLines";

const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
});



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning className={`${roboto.variable}`}>

      <body className="antialiased font-sans dark:bg-zinc-950 ">
        <ThemeProvider>

          <div className="grid grid-cols-[1fr_minmax(0,1024px)_1fr]   w-full overflow-x-hidden">

            <div className="relative  place-items-end   border-zinc-200 dark:border-zinc-800">
              <DiagonalLines />
            </div>


            <div className="w-full max-w-5xl flex flex-col bg-white dark:bg-zinc-950">
              <Navbar />
              <main className="flex-grow">
                {children}
              </main>
              <Footer />
            </div>


            <div className="relative     border-zinc-200 dark:border-zinc-800">
              <DiagonalLines />
            </div>

          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}