import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import { Navbar } from "@/components/layout/Navbar";
import { Footer } from "@/components/layout/Footer";
import { ThemeProvider } from "@/providers/NextThemesProvider";

const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
});



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en"  suppressHydrationWarning className={`${roboto.variable}`}>
      <body
        className={`  antialiased     font-sans dark:bg-zinc-950 `}
      >

        <Navbar />
        <ThemeProvider>
          {children}
        </ThemeProvider>
        <Footer />



      </body>
    </html>
  );
}
